name: Semantic Release & Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Installation de Python et uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: 🚀 Exécution de Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv tool install python-semantic-release
          uvx python-semantic-release version
          uvx python-semantic-release publish