name: Semantic Release & Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Installation de Python et uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: 🚀 Exécution de Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv tool install python-semantic-release
          uvx python-semantic-release version
          uvx python-semantic-release publish

      # --- AJOUT DE LA PARTIE DOC ICI ---
      
      - name: 🔄 Récupération du Changelog mis à jour
        run: git pull origin main # On récupère le commit que le robot vient de faire

      - name: 📚 Génération de la Doc (Sphinx)
        run: uv run sphinx-build -b html docs docs/_build/html

      - name: 📤 Upload de l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy-docs:
    needs: release # On attend que la release soit FINIE
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🚀 Déploiement vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4